version: '3'

services:
  database:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6162:6162"
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure

  frontend:
    container_name: frontend
    build:
     context: .
     dockerfile: ./frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: on-failure

volumes:
  postgres_data:
