version: '3'

services:
  back:
    build: ./back
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
