# Generated by Django 3.2.10 on 2024-04-19 13:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, max_length=30)),
                ('players_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)])),
                ('players_info', models.JSONField(default=dict)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duration_time', models.DurationField(default=datetime.timedelta(seconds=240))),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('registration_starttime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('registration_duration', models.DurationField(default=datetime.timedelta(seconds=1200))),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
