# Generated by Django 5.0.4 on 2024-05-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20240419_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
