# Generated by Django 3.2.10 on 2024-03-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20240330_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
