# Generated by Django 3.2.10 on 2024-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
