# Generated by Django 3.2.10 on 2024-06-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_auto_20240618_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
    ]
