# Generated by Django 4.2.13 on 2024-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_userprofile_update_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='update_from',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
