# Generated by Django 3.2.10 on 2024-06-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_auto_20240618_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player1_notUser',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player2_notUser',
            new_name='player2',
        ),
    ]
