# Generated by Django 3.2.10 on 2024-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_auto_20240606_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='l_matches',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='l_players',
            field=models.JSONField(default=list),
        ),
    ]
