# Generated by Django 3.2.10 on 2024-06-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_auto_20240612_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='elo',
        ),
    ]
